from PyQt5 import QtCore, QtGui, QtWidgets
import sys
import DATABASE
import random

###### VARIAVEIS GLOBAIS #########
id_personagem = 2
#tipo_drop = 0, arma
#tipo_drop = 1, roupa
tipo_drop = 0
id_local = 1
Bonus_monstro = 1.75

#################### CONSTANTES ###################

GANHAR_JOGADOR = 0
GANHAR_MONSTRO = 1

#### OPERAÇÃO REALIZADA NO BD ########



class Ui_Tela_Lugar(QtWidgets.QMainWindow):
    def __init__(self):
        super(Ui_Tela_Lugar, self).__init__()
        self.setupUi()
    def setupUi(self):
        self.ganhou_luta = True
        self.setObjectName("Tela_Lugar")
        self.resize(650, 500)
        self.centralwidget = QtWidgets.QWidget(self)
        self.centralwidget.setObjectName("centralwidget")
        self.botao_voltar_nivel = QtWidgets.QPushButton(self.centralwidget)
        self.botao_voltar_nivel.setGeometry(QtCore.QRect(0, 200, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.botao_voltar_nivel.setFont(font)
        self.botao_voltar_nivel.setObjectName("botao_voltar_nivel")
        self.botao_avancar_nivel = QtWidgets.QPushButton(self.centralwidget)
        self.botao_avancar_nivel.setGeometry(QtCore.QRect(580, 200, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.botao_avancar_nivel.setFont(font)
        self.botao_avancar_nivel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.botao_avancar_nivel.setObjectName("botao_avancar_nivel")
        self.label_lugar = QtWidgets.QLabel(self.centralwidget)
        self.label_lugar.setGeometry(QtCore.QRect(20, 20, 400, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_lugar.setFont(font)
        self.label_lugar.setObjectName("label_lugar")
        self.label_nivel_lugar = QtWidgets.QLabel(self.centralwidget)
        self.label_nivel_lugar.setGeometry(QtCore.QRect(20, 50, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_nivel_lugar.setFont(font)
        self.label_nivel_lugar.setObjectName("label_nivel_lugar")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(130, 110, 160, 251))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_nome_jogador = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_nome_jogador.setFont(font)
        self.label_nome_jogador.setAlignment(QtCore.Qt.AlignCenter)
        self.label_nome_jogador.setObjectName("label_nome_jogador")
        self.verticalLayout.addWidget(self.label_nome_jogador)
        self.label_nivel_jogador = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_nivel_jogador.setFont(font)
        self.label_nivel_jogador.setAlignment(QtCore.Qt.AlignCenter)
        self.label_nivel_jogador.setObjectName("label_nivel_jogador")
        self.verticalLayout.addWidget(self.label_nivel_jogador)
        self.label_roupa = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_roupa.setFont(font)
        self.label_roupa.setAlignment(QtCore.Qt.AlignHCenter | QtCore.Qt.AlignTop)
        self.label_roupa.setObjectName("label_roupa")
        self.verticalLayout.addWidget(self.label_roupa)
        self.label_arma = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_arma.setFont(font)
        self.label_arma.setAlignment(QtCore.Qt.AlignHCenter | QtCore.Qt.AlignTop)
        self.label_arma.setObjectName("label_arma")
        self.verticalLayout.addWidget(self.label_arma)
        self.label_ataque_jogador = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_ataque_jogador.setFont(font)
        self.label_ataque_jogador.setAlignment(QtCore.Qt.AlignHCenter | QtCore.Qt.AlignTop)
        self.label_ataque_jogador.setObjectName("label_ataque_jogador")
        self.verticalLayout.addWidget(self.label_ataque_jogador)
        self.label_defesa_jogador = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_defesa_jogador.setFont(font)
        self.label_defesa_jogador.setAlignment(QtCore.Qt.AlignHCenter | QtCore.Qt.AlignTop)
        self.label_defesa_jogador.setObjectName("label_defesa_jogador")
        self.verticalLayout.addWidget(self.label_defesa_jogador)
        self.botao_fechar = QtWidgets.QPushButton(self.centralwidget)
        self.botao_fechar.setGeometry(QtCore.QRect(580, 0, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.botao_fechar.setFont(font)
        self.botao_fechar.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.botao_fechar.setObjectName("botao_fechar")
        self.botao_inventario = QtWidgets.QPushButton(self.centralwidget)
        self.botao_inventario.setGeometry(QtCore.QRect(220, 400, 100, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.botao_inventario.setFont(font)
        self.botao_inventario.setObjectName("botao_inventario")
        self.botao_guilda = QtWidgets.QPushButton(self.centralwidget)
        self.botao_guilda.setGeometry(QtCore.QRect(90, 400, 100, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.botao_guilda.setFont(font)
        self.botao_guilda.setObjectName("botao_guilda")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(370, 160, 160, 161))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_nome_monstro = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_nome_monstro.setFont(font)
        self.label_nome_monstro.setAlignment(QtCore.Qt.AlignHCenter | QtCore.Qt.AlignTop)
        self.label_nome_monstro.setObjectName("label_nome_monstro")
        self.verticalLayout_2.addWidget(self.label_nome_monstro)
        self.label_ataque_monstro = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_ataque_monstro.setFont(font)
        self.label_ataque_monstro.setAlignment(QtCore.Qt.AlignHCenter | QtCore.Qt.AlignTop)
        self.label_ataque_monstro.setObjectName("label_ataque_monstro")
        self.verticalLayout_2.addWidget(self.label_ataque_monstro)
        self.label_defesa_monstro = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_defesa_monstro.setFont(font)
        self.label_defesa_monstro.setAlignment(QtCore.Qt.AlignHCenter | QtCore.Qt.AlignTop)
        self.label_defesa_monstro.setObjectName("label_defesa_monstro")
        self.verticalLayout_2.addWidget(self.label_defesa_monstro)
        self.botao_lutar = QtWidgets.QPushButton(self.centralwidget)
        self.botao_lutar.setGeometry(QtCore.QRect(400, 400, 100, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.botao_lutar.setFont(font)
        self.botao_lutar.setObjectName("botao_lutar")

        self.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(self)
        self.statusbar.setObjectName("statusbar")
        self.setStatusBar(self.statusbar)

        self.retranslateUi(self)
        QtCore.QMetaObject.connectSlotsByName(self)

        ###### DEFINIR AÇÕES COM OS BOTÕES #########
        self.botao_fechar.clicked.connect(self.Md_Tela_Inicial)
        self.botao_lutar.clicked.connect(self.Md_Tela_Atk_Monstro)
        self.botao_inventario.clicked.connect(self.Md_Tela_Inventario)
        self.botao_voltar_nivel.clicked.connect(self.voltar_nivel)
        self.botao_avancar_nivel.clicked.connect(self.avancar_nivel)

    def avancar_nivel(self):
        LOCAL, NIVEL_LOCAL, id_local = DATABASE.dados_local(id_personagem)
        DATABASE.avancar_local(id_personagem, NIVEL_LOCAL)
        SQL_tela_lugar()


    def voltar_nivel(self):
        LOCAL, NIVEL_LOCAL, id_local = DATABASE.dados_local(id_personagem)
        DATABASE.voltar_local(id_personagem, NIVEL_LOCAL)
        SQL_tela_lugar()

    def Md_Tela_Inventario(self):
        NIVEL_ROUPA, NIVEL_ARMA = DATABASE.itens_usando(id_personagem)
        self.radio_botao_ativo(NIVEL_ROUPA,NIVEL_ARMA)
        NUMERO_ITENS, LINHAS_DA_TABELA = DATABASE.armas_que_possui(id_personagem)
        Contagem = 1
        while NUMERO_ITENS > 0:
            for linha in LINHAS_DA_TABELA:
                if Contagem == 1:
                    tela_inventario.label_arma_nome_1.setText("Nome:\n" + linha[0])
                    tela_inventario.label_arma_nivel_1.setText("Nivel: "+ str(linha[1]))
                    tela_inventario.label_arma_atk_1.setText("Ataque: " + str(linha[2]))
                    tela_inventario.label_arma_def_1.setText("Defesa: " + str(linha[3]))
                    tela_inventario.botao_selecionar_arma_1.setCheckable(True)
                elif Contagem == 2:
                    tela_inventario.label_arma_nome_2.setText("Nome:\n" + linha[0])
                    tela_inventario.label_arma_nivel_2.setText("Nivel: " + str(linha[1]))
                    tela_inventario.label_arma_atk_2.setText("Ataque: " + str(linha[2]))
                    tela_inventario.label_arma_def_2.setText("Defesa: " + str(linha[3]))
                    tela_inventario.botao_selecionar_arma_2.setCheckable(True)
                elif Contagem == 3:
                    tela_inventario.label_arma_nome_3.setText("Nome:\n" + linha[0])
                    tela_inventario.label_arma_nivel_3.setText("Nivel: " + str(linha[1]))
                    tela_inventario.label_arma_atk_3.setText("Ataque: " + str(linha[2]))
                    tela_inventario.label_arma_def_3.setText("Defesa: " + str(linha[3]))
                    tela_inventario.botao_selecionar_arma_3.setCheckable(True)
                elif Contagem == 4:
                    tela_inventario.label_arma_nome_4.setText("Nome:\n" + linha[0])
                    tela_inventario.label_arma_nivel_4.setText("Nivel: " + str(linha[1]))
                    tela_inventario.label_arma_atk_4.setText("Ataque: " + str(linha[2]))
                    tela_inventario.label_arma_def_4.setText("Defesa: " + str(linha[3]))
                    tela_inventario.botao_selecionar_arma_4.setCheckable(True)
                elif Contagem == 5:
                    tela_inventario.label_arma_nome_5.setText("Nome:\n" + linha[0])
                    tela_inventario.label_arma_nivel_5.setText("Nivel: " + str(linha[1]))
                    tela_inventario.label_arma_atk_5.setText("Ataque: " + str(linha[2]))
                    tela_inventario.label_arma_def_5.setText("Defesa: " + str(linha[3]))
                    tela_inventario.botao_selecionar_arma_4.setCheckable(True)
                Contagem = Contagem + 1
                NUMERO_ITENS = NUMERO_ITENS-1
            if Contagem < 6:
                tela_inventario.label_arma_nome_5.setText("BLOQUEADO")
                tela_inventario.label_arma_nivel_5.setText("")
                tela_inventario.label_arma_atk_5.setText("")
                tela_inventario.label_arma_def_5.setText("")
                tela_inventario.botao_selecionar_arma_5.setCheckable(False)
            if Contagem < 5:
                tela_inventario.label_arma_nome_4.setText("BLOQUEADO")
                tela_inventario.label_arma_nivel_4.setText("")
                tela_inventario.label_arma_atk_4.setText("")
                tela_inventario.label_arma_def_4.setText("")
                tela_inventario.botao_selecionar_arma_4.setCheckable(False)
            if Contagem < 4:
                tela_inventario.label_arma_nome_3.setText("BLOQUEADO")
                tela_inventario.label_arma_nivel_3.setText("")
                tela_inventario.label_arma_atk_3.setText("")
                tela_inventario.label_arma_def_3.setText("")
                tela_inventario.botao_selecionar_arma_3.setCheckable(False)
            if Contagem < 3:
                tela_inventario.label_arma_nome_2.setText("BLOQUEADO")
                tela_inventario.label_arma_nivel_2.setText("")
                tela_inventario.label_arma_atk_2.setText("")
                tela_inventario.label_arma_def_2.setText("")
                tela_inventario.botao_selecionar_arma_2.setCheckable(False)
        NUMERO_ITENS, LINHAS_DA_TABELA = DATABASE.roupas_que_possui(id_personagem)
        Contagem = 1
        while NUMERO_ITENS > 0:
            for linha in LINHAS_DA_TABELA:
                if Contagem == 1:
                    tela_inventario.label_roupa_nome_1.setText("Nome:\n" + linha[0])
                    tela_inventario.label_roupa_nivel_1.setText("Nivel: "+ str(linha[1]))
                    tela_inventario.label_roupa_atk_1.setText("Ataque: " + str(linha[2]))
                    tela_inventario.label_roupa_def_1.setText("Defesa: " + str(linha[3]))
                    tela_inventario.botao_selecionar_roupa_1.setCheckable(True)
                elif Contagem == 2:
                    tela_inventario.label_roupa_nome_2.setText("Nome:\n" + linha[0])
                    tela_inventario.label_roupa_nivel_2.setText("Nivel: " + str(linha[1]))
                    tela_inventario.label_roupa_atk_2.setText("Ataque: " + str(linha[2]))
                    tela_inventario.label_roupa_def_2.setText("Defesa: " + str(linha[3]))
                    tela_inventario.botao_selecionar_roupa_2.setCheckable(True)
                elif Contagem == 3:
                    tela_inventario.label_roupa_nome_3.setText("Nome:\n" + linha[0])
                    tela_inventario.label_roupa_nivel_3.setText("Nivel: " + str(linha[1]))
                    tela_inventario.label_roupa_atk_3.setText("Ataque: " + str(linha[2]))
                    tela_inventario.label_roupa_def_3.setText("Defesa: " + str(linha[3]))
                    tela_inventario.botao_selecionar_roupa_3.setCheckable(True)
                elif Contagem == 4:
                    tela_inventario.label_roupa_nome_4.setText("Nome:\n" + linha[0])
                    tela_inventario.label_roupa_nivel_4.setText("Nivel: " + str(linha[1]))
                    tela_inventario.label_roupa_atk_4.setText("Ataque: " + str(linha[2]))
                    tela_inventario.label_roupa_def_4.setText("Defesa: " + str(linha[3]))
                    tela_inventario.botao_selecionar_roupa_4.setCheckable(True)
                elif Contagem == 5:
                    tela_inventario.label_roupa_nome_5.setText("Nome:\n" + linha[0])
                    tela_inventario.label_roupa_nivel_5.setText("Nivel: " + str(linha[1]))
                    tela_inventario.label_roupa_atk_5.setText("Ataque: " + str(linha[2]))
                    tela_inventario.label_roupa_def_5.setText("Defesa: " + str(linha[3]))
                    tela_inventario.botao_selecionar_roupa_5.setCheckable(True)
                Contagem = Contagem + 1
                NUMERO_ITENS = NUMERO_ITENS-1
            if Contagem < 6:
                tela_inventario.label_roupa_nome_5.setText("BLOQUEADO")
                tela_inventario.label_roupa_nivel_5.setText("")
                tela_inventario.label_roupa_atk_5.setText("")
                tela_inventario.label_roupa_def_5.setText("")
                tela_inventario.botao_selecionar_roupa_5.setCheckable(False)
            if Contagem < 5:
                tela_inventario.label_roupa_nome_4.setText("BLOQUEADO")
                tela_inventario.label_roupa_nivel_4.setText("")
                tela_inventario.label_roupa_atk_4.setText("")
                tela_inventario.label_roupa_def_4.setText("")
                tela_inventario.botao_selecionar_roupa_4.setCheckable(False)
            if Contagem < 4:
                tela_inventario.label_roupa_nome_3.setText("BLOQUEADO")
                tela_inventario.label_roupa_nivel_3.setText("")
                tela_inventario.label_roupa_atk_3.setText("")
                tela_inventario.label_roupa_def_3.setText("")
                tela_inventario.botao_selecionar_roupa_3.setCheckable(False)
            if Contagem < 3:
                tela_inventario.label_roupa_nome_2.setText("BLOQUEADO")
                tela_inventario.label_roupa_nivel_2.setText("")
                tela_inventario.label_roupa_atk_2.setText("")
                tela_inventario.label_roupa_def_2.setText("")
                tela_inventario.botao_selecionar_roupa_2.setCheckable(False)
        widget.setCurrentWidget(tela_inventario)

    def Md_Tela_Atk_Monstro(self):
        NOME_MONSTRO, ATK_MONSTRO, DEF_MONSTRO, NIVEL_MONSTRO = DATABASE.dados_monstro(id_personagem)
        tela_atk_monstro.label_nome_monstro.setText(NOME_MONSTRO)
        tela_atk_monstro.label_nivel_monstro.setText(str(NIVEL_MONSTRO))
        tela_atk_monstro.label_atk_monstro.setText(str(ATK_MONSTRO))
        tela_atk_monstro.label_def_monstro.setText(str(DEF_MONSTRO))

        JOGADOR, NIVEL_JOGADOR, ARMA, ROUPA, ATK, DEF = DATABASE.dados_jogador(id_personagem)
        tela_atk_monstro.label_nome_jogador.setText(JOGADOR)
        tela_atk_monstro.label_nivel_jogador.setText(str(NIVEL_JOGADOR))
        tela_atk_monstro.label_atk_jogador.setText(str(ATK))
        tela_atk_monstro.label_def_jogador.setText(str(DEF))

        tela_atk_monstro.label_vitoria.setText("")
        tela_atk_monstro.label_derrota.setText("")
        if self.ganhou_luta == True:
            NOME_DROP, NIVEL_DROP, ATAQUE_DROP, DEFESA_DROP, self.tipo_drop, self.id_prox_drop = DATABASE.prox_drop(id_personagem)
            tela_atk_monstro.label_nome_proximo_drop.setText("Nome:\n" + NOME_DROP)
            tela_atk_monstro.label_nivel_proximo_drop.setText("Nível: " + str(NIVEL_DROP))
            tela_atk_monstro.label_atk_proximo_drop.setText("Ataque: " + str(ATAQUE_DROP))
            tela_atk_monstro.label_def_proximo_drop.setText("Defesa: " + str(DEFESA_DROP))
            tela_atk_monstro.label_proximo_drop.setText("Proximo Drop:")
            self.ganhou_luta = False
        tela_atk_monstro.botao_atacar.blockSignals(False)
        widget.setCurrentWidget(tela_atk_monstro)
    def Md_Tela_Inicial(self):
        sys.exit(app.exec_())
    def radio_botao_ativo(self,NIVEL_ROUPA, NIVEL_ARMA):
        if NIVEL_ROUPA == 1:
            tela_inventario.botao_selecionar_roupa_1.setChecked(True)
        elif NIVEL_ROUPA == 2:
            tela_inventario.botao_selecionar_roupa_2.setChecked(True)
        elif NIVEL_ROUPA == 3:
            tela_inventario.botao_selecionar_roupa_3.setChecked(True)
        elif NIVEL_ROUPA == 4:
            tela_inventario.botao_selecionar_roupa_4.setChecked(True)
        elif NIVEL_ROUPA == 5:
            tela_inventario.botao_selecionar_roupa_5.setChecked(True)
        if NIVEL_ARMA == 1:
            tela_inventario.botao_selecionar_arma_1.setChecked(True)
        elif NIVEL_ARMA == 2:
            tela_inventario.botao_selecionar_arma_2.setChecked(True)
        elif NIVEL_ARMA == 3:
            tela_inventario.botao_selecionar_arma_3.setChecked(True)
        elif NIVEL_ARMA == 4:
            tela_inventario.botao_selecionar_arma_4.setChecked(True)
        elif NIVEL_ARMA == 5:
            tela_inventario.botao_selecionar_arma_5.setChecked(True)

    def retranslateUi(self, Tela_Lugar):
        _translate = QtCore.QCoreApplication.translate
        Tela_Lugar.setWindowTitle(_translate("Tela_Lugar", "MainWindow"))
        self.botao_voltar_nivel.setText(_translate("Tela_Lugar", "<"))
        self.botao_avancar_nivel.setText(_translate("Tela_Lugar", ">"))
        self.label_lugar.setText(_translate("Tela_Lugar", "Lugar:"))
        self.label_nivel_lugar.setText(_translate("Tela_Lugar", "Nível:"))
        self.label_nome_jogador.setText(_translate("Tela_Lugar", "Jogador"))
        self.label_roupa.setText(_translate("Tela_Lugar", "Roupa"))
        self.label_arma.setText(_translate("Tela_Lugar", "Arma"))
        self.label_ataque_jogador.setText(_translate("Tela_Lugar", "Ataque Total:"))
        self.label_defesa_jogador.setText(_translate("Tela_Lugar", "Defesa Total:"))
        self.botao_fechar.setText(_translate("Tela_Lugar", "X"))
        self.botao_inventario.setText(_translate("Tela_Lugar", "Inventário"))
        self.botao_guilda.setText(_translate("Tela_Lugar", "Guildas"))
        self.label_defesa_monstro.setText(_translate("Tela_Lugar", "Defesa:"))
        self.label_nome_monstro.setText(_translate("Tela_Lugar", "Monstro"))
        self.label_ataque_monstro.setText(_translate("Tela_Lugar", "Ataque:"))
        self.botao_lutar.setText(_translate("Tela_Lugar", "Lutar"))
        self.label_nivel_jogador.setText(_translate("Tela_Lugar", "Nível:"))

class Ui_Tela_Atq_Monst(QtWidgets.QMainWindow):
    def __init__(self):
        super(Ui_Tela_Atq_Monst, self).__init__()
        self.setupUi()
    def setupUi(self):
        self.setObjectName("Tela_Atq_Monst")
        self.resize(650, 500)
        self.botao_retorna_lugar = QtWidgets.QPushButton(self)
        self.botao_retorna_lugar.setGeometry(QtCore.QRect(580, 0, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.botao_retorna_lugar.setFont(font)
        self.botao_retorna_lugar.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.botao_retorna_lugar.setObjectName("botao_retorna_lugar")
        self.label_nivel = QtWidgets.QLabel(self)
        self.label_nivel.setGeometry(QtCore.QRect(150, 10, 61, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_nivel.setFont(font)
        self.label_nivel.setObjectName("label_nivel")
        self.label_nome_monstro = QtWidgets.QLabel(self)
        self.label_nome_monstro.setGeometry(QtCore.QRect(20, 70, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_nome_monstro.setFont(font)
        self.label_nome_monstro.setObjectName("label_nome_monstro")
        self.verticalLayoutWidget_12 = QtWidgets.QWidget(self)
        self.verticalLayoutWidget_12.setGeometry(QtCore.QRect(500, 340, 151, 161))
        self.verticalLayoutWidget_12.setObjectName("verticalLayoutWidget_12")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_12)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_nome_proximo_drop = QtWidgets.QLabel(self.verticalLayoutWidget_12)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_nome_proximo_drop.sizePolicy().hasHeightForWidth())
        self.label_nome_proximo_drop.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_nome_proximo_drop.setFont(font)
        self.label_nome_proximo_drop.setMouseTracking(True)
        self.label_nome_proximo_drop.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_nome_proximo_drop.setObjectName("label_nome_proximo_drop")
        self.verticalLayout_5.addWidget(self.label_nome_proximo_drop)
        self.label_nivel_proximo_drop = QtWidgets.QLabel(self.verticalLayoutWidget_12)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_nivel_proximo_drop.setFont(font)
        self.label_nivel_proximo_drop.setObjectName("label_nivel_proximo_drop")
        self.verticalLayout_5.addWidget(self.label_nivel_proximo_drop)
        self.label_atk_proximo_drop = QtWidgets.QLabel(self.verticalLayoutWidget_12)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_atk_proximo_drop.setFont(font)
        self.label_atk_proximo_drop.setObjectName("label_atk_proximo_drop")
        self.verticalLayout_5.addWidget(self.label_atk_proximo_drop)
        self.label_def_proximo_drop = QtWidgets.QLabel(self.verticalLayoutWidget_12)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_def_proximo_drop.setFont(font)
        self.label_def_proximo_drop.setObjectName("label_def_proximo_drop")
        self.verticalLayout_5.addWidget(self.label_def_proximo_drop)
        self.label_proximo_drop = QtWidgets.QLabel(self)
        self.label_proximo_drop.setGeometry(QtCore.QRect(500, 320, 101, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_proximo_drop.setFont(font)
        self.label_proximo_drop.setObjectName("label_proximo_drop")
        self.botao_atacar = QtWidgets.QPushButton(self)
        self.botao_atacar.setGeometry(QtCore.QRect(230, 190, 181, 101))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.botao_atacar.setFont(font)
        self.botao_atacar.setObjectName("botao_atacar")
        self.label_vitoria = QtWidgets.QLabel(self)
        self.label_vitoria.setGeometry(QtCore.QRect(280, 140, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_vitoria.setFont(font)
        self.label_vitoria.setObjectName("label_vitoria")
        self.label_derrota = QtWidgets.QLabel(self)
        self.label_derrota.setGeometry(QtCore.QRect(270, 300, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_derrota.setFont(font)
        self.label_derrota.setObjectName("label_derrota")
        self.label_nome_jogador = QtWidgets.QLabel(self)
        self.label_nome_jogador.setGeometry(QtCore.QRect(20, 30, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_nome_jogador.setFont(font)
        self.label_nome_jogador.setObjectName("label_nome_jogador")
        self.label_nivel_jogador = QtWidgets.QLabel(self)
        self.label_nivel_jogador.setGeometry(QtCore.QRect(160, 40, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_nivel_jogador.setFont(font)
        self.label_nivel_jogador.setAlignment(QtCore.Qt.AlignCenter)
        self.label_nivel_jogador.setObjectName("label_nivel_jogador")
        self.label_nivel_monstro = QtWidgets.QLabel(self)
        self.label_nivel_monstro.setGeometry(QtCore.QRect(160, 70, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_nivel_monstro.setFont(font)
        self.label_nivel_monstro.setAlignment(QtCore.Qt.AlignCenter)
        self.label_nivel_monstro.setObjectName("label_nivel_monstro")
        self.label_atk_jogador = QtWidgets.QLabel(self)
        self.label_atk_jogador.setGeometry(QtCore.QRect(240, 40, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_atk_jogador.setFont(font)
        self.label_atk_jogador.setAlignment(QtCore.Qt.AlignCenter)
        self.label_atk_jogador.setObjectName("label_atk_jogador")
        self.label_atk = QtWidgets.QLabel(self)
        self.label_atk.setGeometry(QtCore.QRect(220, 10, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_atk.setFont(font)
        self.label_atk.setObjectName("label_atk")
        self.label_atk_monstro = QtWidgets.QLabel(self)
        self.label_atk_monstro.setGeometry(QtCore.QRect(240, 70, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_atk_monstro.setFont(font)
        self.label_atk_monstro.setAlignment(QtCore.Qt.AlignCenter)
        self.label_atk_monstro.setObjectName("label_atk_monstro")
        self.label_def_jogador = QtWidgets.QLabel(self)
        self.label_def_jogador.setGeometry(QtCore.QRect(320, 40, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_def_jogador.setFont(font)
        self.label_def_jogador.setAlignment(QtCore.Qt.AlignCenter)
        self.label_def_jogador.setObjectName("label_def_jogador")
        self.label_def = QtWidgets.QLabel(self)
        self.label_def.setGeometry(QtCore.QRect(300, 10, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_def.setFont(font)
        self.label_def.setObjectName("label_def")
        self.label_def_monstro = QtWidgets.QLabel(self)
        self.label_def_monstro.setGeometry(QtCore.QRect(320, 70, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_def_monstro.setFont(font)
        self.label_def_monstro.setAlignment(QtCore.Qt.AlignCenter)
        self.label_def_monstro.setObjectName("label_def_monstro")

        self.retranslateUi(self)
        QtCore.QMetaObject.connectSlotsByName(self)

        #### DEFINIR FUNÇOES DOS BOTÕES ######
        self.botao_retorna_lugar.clicked.connect(self.Md_Tela_Lugar)
        self.botao_atacar.clicked.connect(self.Resultado_luta)

    def Resultado_luta(self):
        NOME_MONSTRO, ATK_MONSTRO, DEF_MONSTRO, NIVEL_MONSTRO = DATABASE.dados_monstro(id_personagem)
        NOME_JOGADOR, NIVEL_JOGADOR, ARMA, ROUPA, ATK, DEF = DATABASE.dados_jogador(id_personagem)
        Probabilidade_jogador = ATK+DEF
        Probabilidade_monstro = ATK_MONSTRO + DEF_MONSTRO

        Resultados_possiveis = [GANHAR_JOGADOR, GANHAR_MONSTRO]
        Vencedor = random.choices(Resultados_possiveis, weights= (Probabilidade_jogador,Probabilidade_monstro*1.75), k=1)
        if Vencedor[0] == GANHAR_JOGADOR:
            self.label_vitoria.setText("Vitória")
            tela_lugar.ganhou_luta = True
            self.label_proximo_drop.setText("Você ganhou!")
            DATABASE.inserir_drop(id_personagem, tela_lugar.id_prox_drop, tela_lugar.tipo_drop)
            DATABASE.nivel_up(id_personagem)
        elif Vencedor[0] == GANHAR_MONSTRO:
            self.label_derrota.setText("Derrota")
        self.botao_atacar.blockSignals(True)

    def Md_Tela_Lugar(self):
        SQL_tela_lugar()
        widget.setCurrentWidget(tela_lugar)

    def retranslateUi(self, Tela_Atq_Monst):
        _translate = QtCore.QCoreApplication.translate
        Tela_Atq_Monst.setWindowTitle(_translate("Tela_Atq_Monst", "Form"))
        self.botao_retorna_lugar.setText(_translate("Tela_Atq_Monst", "X"))
        self.label_nivel.setText(_translate("Tela_Atq_Monst", "Nível"))
        self.label_nome_monstro.setText(_translate("Tela_Atq_Monst", "Monstro"))
        self.label_nome_proximo_drop.setText(_translate("Tela_Atq_Monst", "Nome:"))
        self.label_nivel_proximo_drop.setText(_translate("Tela_Atq_Monst", "Nível:"))
        self.label_atk_proximo_drop.setText(_translate("Tela_Atq_Monst", "Ataque:"))
        self.label_def_proximo_drop.setText(_translate("Tela_Atq_Monst", "Defesa:"))
        self.label_proximo_drop.setText(_translate("Tela_Atq_Monst", "Próximo Drop"))
        self.botao_atacar.setText(_translate("Tela_Atq_Monst", "Atacar"))
        self.label_vitoria.setText(_translate("Tela_Atq_Monst", "Vitória"))
        self.label_derrota.setText(_translate("Tela_Atq_Monst", "Derrota"))
        self.label_nome_jogador.setText(_translate("Tela_Atq_Monst", "Jogador"))
        self.label_nivel_jogador.setText(_translate("Tela_Atq_Monst", "1"))
        self.label_nivel_monstro.setText(_translate("Tela_Atq_Monst", "2"))
        self.label_atk_jogador.setText(_translate("Tela_Atq_Monst", "5"))
        self.label_atk.setText(_translate("Tela_Atq_Monst", "Ataque"))
        self.label_atk_monstro.setText(_translate("Tela_Atq_Monst", "6"))
        self.label_def_jogador.setText(_translate("Tela_Atq_Monst", "4"))
        self.label_def.setText(_translate("Tela_Atq_Monst", "Defesa"))
        self.label_def_monstro.setText(_translate("Tela_Atq_Monst", "7"))

class Ui_Tela_inventario(QtWidgets.QMainWindow):
    def __init__(self):
        super(Ui_Tela_inventario, self).__init__()
        self.setupUi()
    def setupUi(self):
        self.arma_utilizada = 1
        self.roupa_utilizada = 1
        self.setObjectName("Tela_inventario")
        self.resize(650, 500)
        self.label_nome = QtWidgets.QLabel(self)
        self.label_nome.setGeometry(QtCore.QRect(20, 20, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_nome.setFont(font)
        self.label_nome.setObjectName("label_nome")
        self.botao_retorna_lugar = QtWidgets.QPushButton(self)
        self.botao_retorna_lugar.setGeometry(QtCore.QRect(580, 0, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.botao_retorna_lugar.setFont(font)
        self.botao_retorna_lugar.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.botao_retorna_lugar.setObjectName("botao_retorna_lugar")
        self.label_roupas = QtWidgets.QLabel(self)
        self.label_roupas.setGeometry(QtCore.QRect(20, 90, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_roupas.setFont(font)
        self.label_roupas.setObjectName("label_roupas")
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(20, 140, 111, 121))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_1 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_1.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_1.setObjectName("verticalLayout_1")
        self.label_roupa_nome_1 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_roupa_nome_1.sizePolicy().hasHeightForWidth())
        self.label_roupa_nome_1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_roupa_nome_1.setFont(font)
        self.label_roupa_nome_1.setMouseTracking(True)
        self.label_roupa_nome_1.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_roupa_nome_1.setObjectName("label_roupa_nome_1")
        self.verticalLayout_1.addWidget(self.label_roupa_nome_1)
        self.label_roupa_nivel_1 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_roupa_nivel_1.setFont(font)
        self.label_roupa_nivel_1.setObjectName("label_roupa_nivel_1")
        self.verticalLayout_1.addWidget(self.label_roupa_nivel_1)
        self.label_roupa_atk_1 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_roupa_atk_1.setFont(font)
        self.label_roupa_atk_1.setObjectName("label_roupa_atk_1")
        self.verticalLayout_1.addWidget(self.label_roupa_atk_1)
        self.label_roupa_def_1 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_roupa_def_1.setFont(font)
        self.label_roupa_def_1.setObjectName("label_roupa_def_1")
        self.verticalLayout_1.addWidget(self.label_roupa_def_1)
        self.label_Armas = QtWidgets.QLabel(self)
        self.label_Armas.setGeometry(QtCore.QRect(20, 290, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_Armas.setFont(font)
        self.label_Armas.setObjectName("label_Armas")
        self.verticalLayoutWidget_9 = QtWidgets.QWidget(self)
        self.verticalLayoutWidget_9.setGeometry(QtCore.QRect(130, 140, 111, 121))
        self.verticalLayoutWidget_9.setObjectName("verticalLayoutWidget_9")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_9)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_roupa_nome_2 = QtWidgets.QLabel(self.verticalLayoutWidget_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_roupa_nome_2.sizePolicy().hasHeightForWidth())
        self.label_roupa_nome_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_roupa_nome_2.setFont(font)
        self.label_roupa_nome_2.setMouseTracking(True)
        self.label_roupa_nome_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_roupa_nome_2.setObjectName("label_roupa_nome_2")
        self.verticalLayout_2.addWidget(self.label_roupa_nome_2)
        self.label_roupa_nivel_2 = QtWidgets.QLabel(self.verticalLayoutWidget_9)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_roupa_nivel_2.setFont(font)
        self.label_roupa_nivel_2.setObjectName("label_roupa_nivel_2")
        self.verticalLayout_2.addWidget(self.label_roupa_nivel_2)
        self.label_roupa_atk_2 = QtWidgets.QLabel(self.verticalLayoutWidget_9)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_roupa_atk_2.setFont(font)
        self.label_roupa_atk_2.setObjectName("label_roupa_atk_2")
        self.verticalLayout_2.addWidget(self.label_roupa_atk_2)
        self.label_roupa_def_2 = QtWidgets.QLabel(self.verticalLayoutWidget_9)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_roupa_def_2.setFont(font)
        self.label_roupa_def_2.setObjectName("label_roupa_def_2")
        self.verticalLayout_2.addWidget(self.label_roupa_def_2)
        self.verticalLayoutWidget_10 = QtWidgets.QWidget(self)
        self.verticalLayoutWidget_10.setGeometry(QtCore.QRect(350, 140, 111, 121))
        self.verticalLayoutWidget_10.setObjectName("verticalLayoutWidget_10")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_10)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_roupa_nome_4 = QtWidgets.QLabel(self.verticalLayoutWidget_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_roupa_nome_4.sizePolicy().hasHeightForWidth())
        self.label_roupa_nome_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_roupa_nome_4.setFont(font)
        self.label_roupa_nome_4.setMouseTracking(True)
        self.label_roupa_nome_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_roupa_nome_4.setObjectName("label_roupa_nome_4")
        self.verticalLayout_4.addWidget(self.label_roupa_nome_4)
        self.label_roupa_nivel_4 = QtWidgets.QLabel(self.verticalLayoutWidget_10)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_roupa_nivel_4.setFont(font)
        self.label_roupa_nivel_4.setObjectName("label_roupa_nivel_4")
        self.verticalLayout_4.addWidget(self.label_roupa_nivel_4)
        self.label_roupa_atk_4 = QtWidgets.QLabel(self.verticalLayoutWidget_10)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_roupa_atk_4.setFont(font)
        self.label_roupa_atk_4.setObjectName("label_roupa_atk_4")
        self.verticalLayout_4.addWidget(self.label_roupa_atk_4)
        self.label_roupa_def_4 = QtWidgets.QLabel(self.verticalLayoutWidget_10)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_roupa_def_4.setFont(font)
        self.label_roupa_def_4.setObjectName("label_roupa_def_4")
        self.verticalLayout_4.addWidget(self.label_roupa_def_4)
        self.verticalLayoutWidget_11 = QtWidgets.QWidget(self)
        self.verticalLayoutWidget_11.setGeometry(QtCore.QRect(240, 140, 111, 121))
        self.verticalLayoutWidget_11.setObjectName("verticalLayoutWidget_11")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_11)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_roupa_nome_3 = QtWidgets.QLabel(self.verticalLayoutWidget_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_roupa_nome_3.sizePolicy().hasHeightForWidth())
        self.label_roupa_nome_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_roupa_nome_3.setFont(font)
        self.label_roupa_nome_3.setMouseTracking(True)
        self.label_roupa_nome_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_roupa_nome_3.setObjectName("label_roupa_nome_3")
        self.verticalLayout_3.addWidget(self.label_roupa_nome_3)
        self.label_roupa_nivel_3 = QtWidgets.QLabel(self.verticalLayoutWidget_11)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_roupa_nivel_3.setFont(font)
        self.label_roupa_nivel_3.setObjectName("label_roupa_nivel_3")
        self.verticalLayout_3.addWidget(self.label_roupa_nivel_3)
        self.label_roupa_atk_3 = QtWidgets.QLabel(self.verticalLayoutWidget_11)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_roupa_atk_3.setFont(font)
        self.label_roupa_atk_3.setObjectName("label_roupa_atk_3")
        self.verticalLayout_3.addWidget(self.label_roupa_atk_3)
        self.label_roupa_def_3 = QtWidgets.QLabel(self.verticalLayoutWidget_11)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_roupa_def_3.setFont(font)
        self.label_roupa_def_3.setObjectName("label_roupa_def_3")
        self.verticalLayout_3.addWidget(self.label_roupa_def_3)
        self.verticalLayoutWidget_12 = QtWidgets.QWidget(self)
        self.verticalLayoutWidget_12.setGeometry(QtCore.QRect(460, 140, 111, 121))
        self.verticalLayoutWidget_12.setObjectName("verticalLayoutWidget_12")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_12)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_roupa_nome_5 = QtWidgets.QLabel(self.verticalLayoutWidget_12)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_roupa_nome_5.sizePolicy().hasHeightForWidth())
        self.label_roupa_nome_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_roupa_nome_5.setFont(font)
        self.label_roupa_nome_5.setMouseTracking(True)
        self.label_roupa_nome_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_roupa_nome_5.setObjectName("label_roupa_nome_5")
        self.verticalLayout_5.addWidget(self.label_roupa_nome_5)
        self.label_roupa_nivel_5 = QtWidgets.QLabel(self.verticalLayoutWidget_12)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_roupa_nivel_5.setFont(font)
        self.label_roupa_nivel_5.setObjectName("label_roupa_nivel_5")
        self.verticalLayout_5.addWidget(self.label_roupa_nivel_5)
        self.label_roupa_atk_5 = QtWidgets.QLabel(self.verticalLayoutWidget_12)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_roupa_atk_5.setFont(font)
        self.label_roupa_atk_5.setObjectName("label_roupa_atk_5")
        self.verticalLayout_5.addWidget(self.label_roupa_atk_5)
        self.label_roupa_def_5 = QtWidgets.QLabel(self.verticalLayoutWidget_12)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_roupa_def_5.setFont(font)
        self.label_roupa_def_5.setObjectName("label_roupa_def_5")
        self.verticalLayout_5.addWidget(self.label_roupa_def_5)
        self.verticalLayoutWidget_13 = QtWidgets.QWidget(self)
        self.verticalLayoutWidget_13.setGeometry(QtCore.QRect(460, 340, 111, 121))
        self.verticalLayoutWidget_13.setObjectName("verticalLayoutWidget_13")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_13)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_arma_nome_5 = QtWidgets.QLabel(self.verticalLayoutWidget_13)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_arma_nome_5.sizePolicy().hasHeightForWidth())
        self.label_arma_nome_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_arma_nome_5.setFont(font)
        self.label_arma_nome_5.setMouseTracking(True)
        self.label_arma_nome_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_arma_nome_5.setObjectName("label_arma_nome_5")
        self.verticalLayout_10.addWidget(self.label_arma_nome_5)
        self.label_arma_nivel_5 = QtWidgets.QLabel(self.verticalLayoutWidget_13)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_arma_nivel_5.setFont(font)
        self.label_arma_nivel_5.setObjectName("label_arma_nivel_5")
        self.verticalLayout_10.addWidget(self.label_arma_nivel_5)
        self.label_arma_atk_5 = QtWidgets.QLabel(self.verticalLayoutWidget_13)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_arma_atk_5.setFont(font)
        self.label_arma_atk_5.setObjectName("label_arma_atk_5")
        self.verticalLayout_10.addWidget(self.label_arma_atk_5)
        self.label_arma_def_5 = QtWidgets.QLabel(self.verticalLayoutWidget_13)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_arma_def_5.setFont(font)
        self.label_arma_def_5.setObjectName("label_arma_def_5")
        self.verticalLayout_10.addWidget(self.label_arma_def_5)
        self.verticalLayoutWidget_14 = QtWidgets.QWidget(self)
        self.verticalLayoutWidget_14.setGeometry(QtCore.QRect(350, 340, 111, 121))
        self.verticalLayoutWidget_14.setObjectName("verticalLayoutWidget_14")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_14)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_arma_nome_4 = QtWidgets.QLabel(self.verticalLayoutWidget_14)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_arma_nome_4.sizePolicy().hasHeightForWidth())
        self.label_arma_nome_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_arma_nome_4.setFont(font)
        self.label_arma_nome_4.setMouseTracking(True)
        self.label_arma_nome_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_arma_nome_4.setObjectName("label_arma_nome_4")
        self.verticalLayout_11.addWidget(self.label_arma_nome_4)
        self.label_arma_nivel_4 = QtWidgets.QLabel(self.verticalLayoutWidget_14)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_arma_nivel_4.setFont(font)
        self.label_arma_nivel_4.setObjectName("label_arma_nivel_4")
        self.verticalLayout_11.addWidget(self.label_arma_nivel_4)
        self.label_arma_atk_4 = QtWidgets.QLabel(self.verticalLayoutWidget_14)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_arma_atk_4.setFont(font)
        self.label_arma_atk_4.setObjectName("label_arma_atk_4")
        self.verticalLayout_11.addWidget(self.label_arma_atk_4)
        self.label_arma_def_4 = QtWidgets.QLabel(self.verticalLayoutWidget_14)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_arma_def_4.setFont(font)
        self.label_arma_def_4.setObjectName("label_arma_def_4")
        self.verticalLayout_11.addWidget(self.label_arma_def_4)
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(self)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(20, 340, 111, 121))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_arma_nome_1 = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_arma_nome_1.sizePolicy().hasHeightForWidth())
        self.label_arma_nome_1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_arma_nome_1.setFont(font)
        self.label_arma_nome_1.setMouseTracking(True)
        self.label_arma_nome_1.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_arma_nome_1.setObjectName("label_arma_nome_1")
        self.verticalLayout_6.addWidget(self.label_arma_nome_1)
        self.label_arma_nivel_1 = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_arma_nivel_1.setFont(font)
        self.label_arma_nivel_1.setObjectName("label_arma_nivel_1")
        self.verticalLayout_6.addWidget(self.label_arma_nivel_1)
        self.label_arma_atk_1 = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_arma_atk_1.setFont(font)
        self.label_arma_atk_1.setObjectName("label_arma_atk_1")
        self.verticalLayout_6.addWidget(self.label_arma_atk_1)
        self.label_arma_def_1 = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_arma_def_1.setFont(font)
        self.label_arma_def_1.setObjectName("label_arma_def_1")
        self.verticalLayout_6.addWidget(self.label_arma_def_1)
        self.verticalLayoutWidget_15 = QtWidgets.QWidget(self)
        self.verticalLayoutWidget_15.setGeometry(QtCore.QRect(130, 340, 111, 121))
        self.verticalLayoutWidget_15.setObjectName("verticalLayoutWidget_15")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_15)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_arma_nome_2 = QtWidgets.QLabel(self.verticalLayoutWidget_15)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_arma_nome_2.sizePolicy().hasHeightForWidth())
        self.label_arma_nome_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_arma_nome_2.setFont(font)
        self.label_arma_nome_2.setMouseTracking(True)
        self.label_arma_nome_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_arma_nome_2.setObjectName("label_arma_nome_2")
        self.verticalLayout_7.addWidget(self.label_arma_nome_2)
        self.label_arma_nivel_2 = QtWidgets.QLabel(self.verticalLayoutWidget_15)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_arma_nivel_2.setFont(font)
        self.label_arma_nivel_2.setObjectName("label_arma_nivel_2")
        self.verticalLayout_7.addWidget(self.label_arma_nivel_2)
        self.label_arma_atk_2 = QtWidgets.QLabel(self.verticalLayoutWidget_15)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_arma_atk_2.setFont(font)
        self.label_arma_atk_2.setObjectName("label_arma_atk_2")
        self.verticalLayout_7.addWidget(self.label_arma_atk_2)
        self.label_arma_def_2 = QtWidgets.QLabel(self.verticalLayoutWidget_15)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_arma_def_2.setFont(font)
        self.label_arma_def_2.setObjectName("label_arma_def_2")
        self.verticalLayout_7.addWidget(self.label_arma_def_2)
        self.verticalLayoutWidget_16 = QtWidgets.QWidget(self)
        self.verticalLayoutWidget_16.setGeometry(QtCore.QRect(240, 340, 111, 121))
        self.verticalLayoutWidget_16.setObjectName("verticalLayoutWidget_16")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_16)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_arma_nome_3 = QtWidgets.QLabel(self.verticalLayoutWidget_16)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_arma_nome_3.sizePolicy().hasHeightForWidth())
        self.label_arma_nome_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_arma_nome_3.setFont(font)
        self.label_arma_nome_3.setMouseTracking(True)
        self.label_arma_nome_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_arma_nome_3.setObjectName("label_arma_nome_3")
        self.verticalLayout_8.addWidget(self.label_arma_nome_3)
        self.label_arma_nivel_3 = QtWidgets.QLabel(self.verticalLayoutWidget_16)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_arma_nivel_3.setFont(font)
        self.label_arma_nivel_3.setObjectName("label_arma_nivel_3")
        self.verticalLayout_8.addWidget(self.label_arma_nivel_3)
        self.label_arma_atk_3 = QtWidgets.QLabel(self.verticalLayoutWidget_16)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_arma_atk_3.setFont(font)
        self.label_arma_atk_3.setObjectName("label_arma_atk_3")
        self.verticalLayout_8.addWidget(self.label_arma_atk_3)
        self.label_arma_def_3 = QtWidgets.QLabel(self.verticalLayoutWidget_16)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_arma_def_3.setFont(font)
        self.label_arma_def_3.setObjectName("label_arma_def_3")
        self.verticalLayout_8.addWidget(self.label_arma_def_3)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 260, 551, 20))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.botao_selecionar_roupa_1 = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.botao_selecionar_roupa_1.setText("")
        self.botao_selecionar_roupa_1.setObjectName("botao_selecionar_roupa_1")
        self.horizontalLayout.addWidget(self.botao_selecionar_roupa_1)
        self.botao_selecionar_roupa_2 = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.botao_selecionar_roupa_2.setText("")
        self.botao_selecionar_roupa_2.setObjectName("botao_selecionar_roupa_2")
        self.horizontalLayout.addWidget(self.botao_selecionar_roupa_2)
        self.botao_selecionar_roupa_3 = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.botao_selecionar_roupa_3.setText("")
        self.botao_selecionar_roupa_3.setObjectName("botao_selecionar_roupa_3")
        self.horizontalLayout.addWidget(self.botao_selecionar_roupa_3)
        self.botao_selecionar_roupa_4 = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.botao_selecionar_roupa_4.setText("")
        self.botao_selecionar_roupa_4.setObjectName("botao_selecionar_roupa_4")
        self.horizontalLayout.addWidget(self.botao_selecionar_roupa_4)
        self.botao_selecionar_roupa_5 = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.botao_selecionar_roupa_5.setText("")
        self.botao_selecionar_roupa_5.setObjectName("botao_selecionar_roupa_5")
        self.horizontalLayout.addWidget(self.botao_selecionar_roupa_5)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(20, 460, 551, 20))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.botao_selecionar_arma_1 = QtWidgets.QRadioButton(self.horizontalLayoutWidget_2)
        self.botao_selecionar_arma_1.setText("")
        self.botao_selecionar_arma_1.setObjectName("botao_selecionar_arma_1")
        self.horizontalLayout_2.addWidget(self.botao_selecionar_arma_1)
        self.botao_selecionar_arma_2 = QtWidgets.QRadioButton(self.horizontalLayoutWidget_2)
        self.botao_selecionar_arma_2.setText("")
        self.botao_selecionar_arma_2.setObjectName("botao_selecionar_arma_2")
        self.horizontalLayout_2.addWidget(self.botao_selecionar_arma_2)
        self.botao_selecionar_arma_3 = QtWidgets.QRadioButton(self.horizontalLayoutWidget_2)
        self.botao_selecionar_arma_3.setText("")
        self.botao_selecionar_arma_3.setObjectName("botao_selecionar_arma_3")
        self.horizontalLayout_2.addWidget(self.botao_selecionar_arma_3)
        self.botao_selecionar_arma_4 = QtWidgets.QRadioButton(self.horizontalLayoutWidget_2)
        self.botao_selecionar_arma_4.setText("")
        self.botao_selecionar_arma_4.setObjectName("botao_selecionar_arma_4")
        self.horizontalLayout_2.addWidget(self.botao_selecionar_arma_4)
        self.botao_selecionar_arma_5 = QtWidgets.QRadioButton(self.horizontalLayoutWidget_2)
        self.botao_selecionar_arma_5.setText("")
        self.botao_selecionar_arma_5.setObjectName("botao_selecionar_arma_5")
        self.horizontalLayout_2.addWidget(self.botao_selecionar_arma_5)

        self.retranslateUi(self)
        QtCore.QMetaObject.connectSlotsByName(self)
        ##### DEFINIR FUNÇÃO DOS BOTÕES ###########

        self.botao_retorna_lugar.clicked.connect(self.Md_Tela_Lugar)

    def Md_Tela_Lugar(self):
        if(self.botao_selecionar_arma_1.isChecked()):
            self.arma_utilizada = 1
        elif (self.botao_selecionar_arma_2.isChecked()):
            self.arma_utilizada = 2
        elif (self.botao_selecionar_arma_3.isChecked()):
            self.arma_utilizada = 3
        elif (self.botao_selecionar_arma_4.isChecked()):
            self.arma_utilizada = 4
        elif (self.botao_selecionar_arma_5.isChecked()):
            self.arma_utilizada = 5
        if (self.botao_selecionar_roupa_1.isChecked()):
            self.roupa_utilizada = 1
        elif (self.botao_selecionar_roupa_2.isChecked()):
            self.roupa_utilizada = 2
        elif (self.botao_selecionar_roupa_3.isChecked()):
            self.roupa_utilizada = 3
        elif (self.botao_selecionar_roupa_4.isChecked()):
            self.roupa_utilizada = 4
        elif (self.botao_selecionar_roupa_5.isChecked()):
            self.roupa_utilizada = 5
        DATABASE.atualizar_armas(id_personagem,self.arma_utilizada,self.roupa_utilizada)
        SQL_tela_lugar()
        widget.setCurrentWidget(tela_lugar)

    def retranslateUi(self, Tela_inventario):
        _translate = QtCore.QCoreApplication.translate
        Tela_inventario.setWindowTitle(_translate("Tela_inventario", "Form"))
        self.label_nome.setText(_translate("Tela_inventario", "Inventário"))
        self.botao_retorna_lugar.setText(_translate("Tela_inventario", "X"))
        self.label_roupas.setText(_translate("Tela_inventario", "Roupas"))
        self.label_roupa_nome_1.setText(_translate("Tela_inventario", "Nome:"))
        self.label_roupa_nivel_1.setText(_translate("Tela_inventario", "Nível:"))
        self.label_roupa_atk_1.setText(_translate("Tela_inventario", "Ataque:"))
        self.label_roupa_def_1.setText(_translate("Tela_inventario", "Defesa:"))
        self.label_Armas.setText(_translate("Tela_inventario", "Armas"))
        self.label_roupa_nome_2.setText(_translate("Tela_inventario", "Nome:"))
        self.label_roupa_nivel_2.setText(_translate("Tela_inventario", "Nível:"))
        self.label_roupa_atk_2.setText(_translate("Tela_inventario", "Ataque:"))
        self.label_roupa_def_2.setText(_translate("Tela_inventario", "Defesa:"))
        self.label_roupa_nome_4.setText(_translate("Tela_inventario", "Nome:"))
        self.label_roupa_nivel_4.setText(_translate("Tela_inventario", "Nível:"))
        self.label_roupa_atk_4.setText(_translate("Tela_inventario", "Ataque:"))
        self.label_roupa_def_4.setText(_translate("Tela_inventario", "Defesa:"))
        self.label_roupa_nome_3.setText(_translate("Tela_inventario", "Nome:"))
        self.label_roupa_nivel_3.setText(_translate("Tela_inventario", "Nível:"))
        self.label_roupa_atk_3.setText(_translate("Tela_inventario", "Ataque:"))
        self.label_roupa_def_3.setText(_translate("Tela_inventario", "Defesa:"))
        self.label_roupa_nome_5.setText(_translate("Tela_inventario", "Nome:"))
        self.label_roupa_nivel_5.setText(_translate("Tela_inventario", "Nível:"))
        self.label_roupa_atk_5.setText(_translate("Tela_inventario", "Ataque:"))
        self.label_roupa_def_5.setText(_translate("Tela_inventario", "Defesa:"))
        self.label_arma_nome_5.setText(_translate("Tela_inventario", "Nome:"))
        self.label_arma_nivel_5.setText(_translate("Tela_inventario", "Nível:"))
        self.label_arma_atk_5.setText(_translate("Tela_inventario", "Ataque:"))
        self.label_arma_def_5.setText(_translate("Tela_inventario", "Defesa:"))
        self.label_arma_nome_4.setText(_translate("Tela_inventario", "Nome:"))
        self.label_arma_nivel_4.setText(_translate("Tela_inventario", "Nível:"))
        self.label_arma_atk_4.setText(_translate("Tela_inventario", "Ataque:"))
        self.label_arma_def_4.setText(_translate("Tela_inventario", "Defesa:"))
        self.label_arma_nome_1.setText(_translate("Tela_inventario", "Nome:"))
        self.label_arma_nivel_1.setText(_translate("Tela_inventario", "Nível:"))
        self.label_arma_atk_1.setText(_translate("Tela_inventario", "Ataque:"))
        self.label_arma_def_1.setText(_translate("Tela_inventario", "Defesa:"))
        self.label_arma_nome_2.setText(_translate("Tela_inventario", "Nome:"))
        self.label_arma_nivel_2.setText(_translate("Tela_inventario", "Nível:"))
        self.label_arma_atk_2.setText(_translate("Tela_inventario", "Ataque:"))
        self.label_arma_def_2.setText(_translate("Tela_inventario", "Defesa:"))
        self.label_arma_nome_3.setText(_translate("Tela_inventario", "Nome:"))
        self.label_arma_nivel_3.setText(_translate("Tela_inventario", "Nível:"))
        self.label_arma_atk_3.setText(_translate("Tela_inventario", "Ataque:"))
        self.label_arma_def_3.setText(_translate("Tela_inventario", "Defesa:"))


def SQL_tela_lugar():
    widget.setCurrentWidget(tela_lugar)
    LOCAL, NIVEL_LOCAL, id_local = DATABASE.dados_local(id_personagem)
    JOGADOR, NIVEL_JOGADOR, ARMA, ROUPA, ATK, DEF = DATABASE.dados_jogador(id_personagem)
    NOME_MONSTRO, ATK_MONSTRO, DEF_MONSTRO, NIVEL = DATABASE.dados_monstro(id_personagem)
    tela_lugar.label_lugar.setText("Lugar: " + LOCAL)
    tela_lugar.label_nivel_lugar.setText("Nivel: " + str(NIVEL_LOCAL))
    if NIVEL_LOCAL == 1:
        tela_lugar.botao_voltar_nivel.blockSignals(True)
    else:
        tela_lugar.botao_voltar_nivel.blockSignals(False)
    if NIVEL_LOCAL == 5 or NIVEL_JOGADOR == NIVEL_LOCAL:
        tela_lugar.botao_avancar_nivel.blockSignals(True)
    else:
        tela_lugar.botao_avancar_nivel.blockSignals(False)
    tela_lugar.label_nome_jogador.setText(JOGADOR)
    tela_lugar.label_nivel_jogador.setText("Nivel: " + str(NIVEL_JOGADOR))
    tela_lugar.label_arma.setText("Arma\n" + ARMA)
    tela_lugar.label_roupa.setText("Roupa\n" + ROUPA)
    tela_lugar.label_ataque_jogador.setText("Ataque Total\n" + str(ATK))
    tela_lugar.label_defesa_jogador.setText("Defesa Total\n" + str(DEF))
    tela_lugar.label_nome_monstro.setText("Monstro\n" + NOME_MONSTRO)
    tela_lugar.label_ataque_monstro.setText("Ataque:\n" + str(ATK_MONSTRO))
    tela_lugar.label_defesa_monstro.setText("Defesa:\n" + str(DEF_MONSTRO))


if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    widget = QtWidgets.QStackedWidget()
    widget.setFixedHeight(500)
    widget.setFixedWidth(650)
    #### INSERIR TELAS ######
    tela_lugar = Ui_Tela_Lugar()
    widget.addWidget(tela_lugar)  # create an instance of the first page class and add it to stackedwidget

    tela_atk_monstro = Ui_Tela_Atq_Monst()
    widget.addWidget(tela_atk_monstro)

    tela_inventario = Ui_Tela_inventario()
    widget.addWidget(tela_inventario)

    SQL_tela_lugar()


    widget.show()
    app.exec_()