# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Tela_Criar_Guilda.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Tela_Criar_Guilda(object):
    def setupUi(self, Tela_Criar_Guilda):
        Tela_Criar_Guilda.setObjectName("Tela_Criar_Guilda")
        Tela_Criar_Guilda.resize(400, 300)
        self.label_nome = QtWidgets.QLabel(Tela_Criar_Guilda)
        self.label_nome.setGeometry(QtCore.QRect(130, 60, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_nome.setFont(font)
        self.label_nome.setObjectName("label_nome")
        self.line_edit_nome = QtWidgets.QLineEdit(Tela_Criar_Guilda)
        self.line_edit_nome.setGeometry(QtCore.QRect(140, 160, 113, 22))
        self.line_edit_nome.setObjectName("line_edit_nome")
        self.label_nome_guilda = QtWidgets.QLabel(Tela_Criar_Guilda)
        self.label_nome_guilda.setGeometry(QtCore.QRect(150, 130, 101, 21))
        self.label_nome_guilda.setObjectName("label_nome_guilda")
        self.botao_selecionar = QtWidgets.QPushButton(Tela_Criar_Guilda)
        self.botao_selecionar.setGeometry(QtCore.QRect(130, 190, 131, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.botao_selecionar.setFont(font)
        self.botao_selecionar.setObjectName("botao_selecionar")

        self.retranslateUi(Tela_Criar_Guilda)
        QtCore.QMetaObject.connectSlotsByName(Tela_Criar_Guilda)

    def retranslateUi(self, Tela_Criar_Guilda):
        _translate = QtCore.QCoreApplication.translate
        Tela_Criar_Guilda.setWindowTitle(_translate("Tela_Criar_Guilda", "Form"))
        self.label_nome.setText(_translate("Tela_Criar_Guilda", "Criar Guilda"))
        self.label_nome_guilda.setText(_translate("Tela_Criar_Guilda", "Nome da Guilda"))
        self.botao_selecionar.setText(_translate("Tela_Criar_Guilda", "Selecionar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Tela_Criar_Guilda = QtWidgets.QWidget()
    ui = Ui_Tela_Criar_Guilda()
    ui.setupUi(Tela_Criar_Guilda)
    Tela_Criar_Guilda.show()
    sys.exit(app.exec_())
